language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

before_script:
  - travis_retry composer update --no-interaction

script: pushd test && phpunit --configuration phpunit.xml --debug --verbose && popd
